### ISSUE TITLE
Addition of individual vHost data to overall statistics

### ISSUE THREAD

**Issue by Django-BOfH** [eldy/AWStats#268] opened 2024-11-23 19:56 UTC
Is there actually a way to combine the statistical data of individual (v) hosts into a single overall statistic?

What do I mean? Well, I have different vhosts, such as vhost1.example.com, vhost2.example.com and vhost3.example.com. Now I have three individual statistics that awstats provides me with. But now it would also be interesting to know how many hits, for example, all pages together have and what total traffic they cause in sum. 

Is there a simple solution to this task, or do I have to continue to add them up manually?

**Comment by chuckhoupt** [comment] 2024-11-23 21:35
You might try [AWStats Totals](https://www.telartis.nl/en/awstats) -- I use it show overall stats across many domains/sub-domains. 

 It produces a page that looks like this:

![AWStats-Totals](https://github.com/user-attachments/assets/3e7827d4-0da4-4b2d-b0f1-446a7737381d)

**Comment by Django-BOfH** [comment] 2024-11-25 09:59
Sounds very interesting, but eighter I'm stupid or I didn't look right. On [GitHub-Repo](https://www.telartis.nl/en/awstats) I found no documentation, where's to place those php-scrips or how must or can I configure, where are my awstats-data are placed. So I think and hope, you can kick me in the right direction ... ;) 

ahhhh, some installation instructions are inside the two php-scripts!

Fantastic, that's exactly what I was looking for! YMMD!

**Comment by Django-BOfH** [comment] 2024-11-25 10:24
Fantastic, [AWStats Totals](https://www.telartis.nl/en/awstats) was exactly what I was looking for! YMMD!

**Comment by chuckhoupt** [comment] 2024-11-25 12:25
Great. Don't forget to close this ticket since the issue is solved.

**Closed as completed** 2024-11-25 12:28 UTC
